version: "3.9"

services:
  app:
    image: file_storage
    container_name: "file_storage_app"
    ports:
      - "8082:8080"
  postgres:
    image: postgres:14.11
    container_name: "postgres"
    volumes:
      - postgres_data_file_storage:/var/lib/postgres/data/
    ports:
      - "5433:5432"
    environment: #TODO: change user, password
      POSTGRES_DB: file_storage
      POSTGRES_USER: vladislavmedvedev
      POSTGRES_PASSWORD: 123
    restart: always

volumes:
  postgres_data_file_storage:

