version: "3.9"

services:
  app:
    image: file_storage
    container_name: "file_storage_app"
    ports:
      - "8082:8080"
    environment:
      POSTGRES_DB: file_storage
      MINIO_URL: http://minio:9000
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      MINIO_USER: ${MINIO_USER}
      MINIO_PASSWORD: ${MINIO_PASSWORD}
    depends_on:
      - postgres
      - minio
    restart: always


  postgres:
    image: postgres:14.11
    container_name: "postgres"
    volumes:
      - postgres_data_file_storage:/var/lib/postgres/data/
    environment:
      POSTGRES_DB: file_storage
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always

  minio:
    image: quay.io/minio/minio
    container_name: "minio"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data_file_storage:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always

volumes:
  postgres_data_file_storage:
  minio_data_file_storage:
