# container stack for local development
version: "3.9"

services:
  postgres:
    image: postgres:14.11
    container_name: "postgres-dev"
    volumes:
      - postgres_data_file_storage_dev:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: file_storage
      POSTGRES_USER: vladislavmedvedev
      POSTGRES_PASSWORD: 123
    restart: always

  minio:
    image: quay.io/minio/minio
    container_name: "minio-dev"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data_file_storage_dev:/data
    environment:
      - MINIO_ROOT_USER=vladislavmedvedev
      - MINIO_ROOT_PASSWORD=123123123
    ports:
      - "9002:9000"
      - "9003:9001"
    restart: always


volumes:
  postgres_data_file_storage_dev:
  minio_data_file_storage_dev: