spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5434/file_storage
    username: vladislavmedvedev
    password: 123
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
