spring:

  mvc:
    hidden method:
      filter:
        enabled: true

  datasource:
    url: jdbc:postgresql://127.0.0.1:5434/file_storage
    username: vladislavmedvedev
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop

  minio:
    client:
      endpoint: http://localhost:9002
      username: vladislavmedvedev
      password: 123123123
      bucket-name: user-files